// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPUdJ-y-06jN-p5uV2RQ4CLwqC9BzHY_M',
    appId: '1:563940753045:web:5dc8315ea9c8cfbd71659c',
    messagingSenderId: '563940753045',
    projectId: 'gymmanagement-2b761',
    authDomain: 'gymmanagement-2b761.firebaseapp.com',
    storageBucket: 'gymmanagement-2b761.appspot.com',
    measurementId: 'G-2WS9P14KW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHL_iBi9GYB6nblnaauYQsXcDIhbis-gA',
    appId: '1:563940753045:android:19a33469360ace2471659c',
    messagingSenderId: '563940753045',
    projectId: 'gymmanagement-2b761',
    storageBucket: 'gymmanagement-2b761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-g8mvcyW8LynMuJH-_YDVHlHRjBcJvM',
    appId: '1:563940753045:ios:e24149666e479b7571659c',
    messagingSenderId: '563940753045',
    projectId: 'gymmanagement-2b761',
    storageBucket: 'gymmanagement-2b761.appspot.com',
    iosBundleId: 'com.example.gymManagement2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-g8mvcyW8LynMuJH-_YDVHlHRjBcJvM',
    appId: '1:563940753045:ios:57db9620ab69b4e971659c',
    messagingSenderId: '563940753045',
    projectId: 'gymmanagement-2b761',
    storageBucket: 'gymmanagement-2b761.appspot.com',
    iosBundleId: 'com.example.gymManagement2.RunnerTests',
  );
}
